# Generated by Django 5.1.4 on 2025-01-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP_Cadastro', '0004_fornecedor_lojas_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito'), ('dinheiro', 'Dinheiro'), ('combinado', 'Combinado')], max_length=255)),
                ('codigo_venda', models.CharField(max_length=100, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.cliente')),
                ('produtos', models.ManyToManyField(to='APP_Cadastro.produtos')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.funcionario')),
            ],
        ),
    ]
