# Generated by Django 5.1.4 on 2025-01-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_venda',
        ),
    ]
