# Generated by Django 5.1.4 on 2025-01-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Cadastro', '0004_fornecedor_lojas_produtos'),
        ('APP_Vendas', '0002_remove_venda_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.lojas'),
            preserve_default=False,
        ),
    ]
