# Generated by Django 5.1.4 on 2024-12-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=200)),
                ('Cidade', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=200)),
                ('numeroResidencial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=200)),
                ('Cidade', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=200)),
                ('numeroResidencial', models.CharField(max_length=100)),
            ],
        ),
    ]
