# Generated by Django 5.1.4 on 2025-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Cadastro', '0003_rename_bairro_cliente_bairro_rename_cep_cliente_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=200)),
                ('numeroResidencial', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id_loja', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=200)),
                ('numeroResidencial', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('unidadeMedida', models.CharField(max_length=100)),
            ],
        ),
    ]
