# Generated by Django 5.1.4 on 2025-01-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP_Cadastro', '0004_fornecedor_lojas_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('id_requisicao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_solicitada', models.IntegerField()),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=10)),
                ('coordenador_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP_Cadastro.funcionario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.produtos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.lojas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('status_pedido', models.CharField(choices=[('A', 'Aprovado'), ('P', 'Pendente'), ('R', 'Rejeitado')], default='P', max_length=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Cadastro.lojas')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Estoque.requisicaocompra')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
